In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6957, 9577, 8957, 6915],
 [6957, 9577, 8957, 4320],
 [6957, 8802, 8957, 1335],
 [8264, 6620, 3049, 1762, 9979],
 [8264, 6620, 3049, 1762, 2048],
 [6049, 6957, 1339, 8957, 7525],
 [2854, 6451, 1689, 1762]]

# One-Hot Representation in NLP

## Import

```python
from tensorflow.keras.preprocessing.text import one_hot
```

The `one_hot()` function is used to **convert each word in a sentence into a unique integer index**.

It is one of the simplest methods to represent text numerically before feeding it into a Deep Learning model.

---

# Step 1: Create Sentences

```python
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]
```

These are the input sentences (corpus) that we want to convert into numerical form.

---

# Step 2: Define Vocabulary Size

```python
voc_size = 10000
```

`voc_size` represents the **maximum vocabulary size**.

- TensorFlow maps each word to an integer between **1** and **9999**.
- A larger vocabulary size reduces the chance of different words getting the same index (collision).

Example:

```text
Vocabulary Size = 10000

Possible Word IDs:

1
25
786
1543
9999
```

---

# Step 3: One-Hot Representation

```python
one_hot_repr = [one_hot(words, voc_size) for words in sent]
```

This line performs the following steps:

1. Takes one sentence at a time.
2. Splits the sentence into individual words.
3. Converts each word into a unique integer index using the specified vocabulary size.
4. Stores the encoded sentence as a list of integers.

---

# Example

Sentence:

```text
the glass of milk
```

Possible Output:

```text
[345, 7821, 126, 987]
```

Sentence:

```text
I am a good boy
```

Possible Output:

```text
[54, 621, 902, 1843, 321]
```

> **Note:** The exact numbers may change every time because TensorFlow uses a **hashing technique** to assign word indices.

---

# What Does `one_hot()` Actually Do?

It **does not create a traditional one-hot vector** like:

```text
Cat → [0,0,1,0,0]
```

Instead, TensorFlow's `one_hot()` function returns **integer word indices** using hashing.

Example:

```text
good      → 432
developer → 1987
glass     → 678
milk      → 999
```

These integer IDs are later used by an **Embedding Layer** to generate dense vector representations.

---

# Why Do We Need One-Hot Representation?

Deep Learning models cannot understand text directly.

For example:

```text
"I love AI"
```

A neural network cannot process words.

So we first convert them into numbers:

```text
"I love AI"

↓

[245, 983, 412]
```

Now the model can process the numerical data.

---

# Limitations

- Uses **hashing**, so two different words may sometimes get the same index (collision).
- Does not capture the **meaning** or **relationship** between words.
- Returns only integer IDs, not actual feature vectors.

Because of these limitations, **Embedding Layers** are commonly used after one-hot encoding.

---

# Workflow

```text
Sentence
      ↓
Split into Words
      ↓
One-Hot Encoding
      ↓
Integer IDs
      ↓
Embedding Layer
      ↓
Dense Word Vectors
      ↓
RNN / LSTM / GRU
```

---

# Key Points ⭐

- `one_hot()` converts words into **integer indices**.
- `voc_size` defines the maximum vocabulary size.
- TensorFlow uses **hashing** to generate word IDs.
- The output is a **list of integers**, not binary vectors.
- These integer IDs are used as input to the **Embedding Layer**.
- One-hot representation is an initial step in many NLP pipelines.

---

# Interview Questions

### 1. What is One-Hot Representation in TensorFlow?

**Answer:**  
The `one_hot()` function converts words into unique integer indices using a hashing technique. These indices are later used by embedding layers.

---

### 2. What is the purpose of `voc_size`?

**Answer:**  
It specifies the maximum vocabulary size and defines the range of possible word indices.

---

### 3. Does TensorFlow's `one_hot()` create binary one-hot vectors?

**Answer:**  
No. It returns **integer word indices**, not binary vectors. The name can be misleading.

---

### 4. Why do we convert text into numbers?

**Answer:**  
Neural networks perform mathematical operations only on numerical data. Therefore, text must first be converted into numerical representations.

---

### 5. What is the limitation of `one_hot()`?

**Answer:**  
It uses hashing, which may cause collisions, and it does not capture semantic meaning or relationships between words.
````


In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6957 9577 8957 6915]
 [   0    0    0    0 6957 9577 8957 4320]
 [   0    0    0    0 6957 8802 8957 1335]
 [   0    0    0 8264 6620 3049 1762 9979]
 [   0    0    0 8264 6620 3049 1762 2048]
 [   0    0    0 6049 6957 1339 8957 7525]
 [   0    0    0    0 2854 6451 1689 1762]]


# Word Embedding Representation

## Import Required Libraries

```python
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
```

### Explanation

- **Embedding** → Converts integer word IDs into dense vector representations (word embeddings).
- **pad_sequences** → Makes all input sequences the same length by adding padding.
- **Sequential** → Used to build a neural network layer by layer.
- **NumPy** → Used for numerical operations.

---

## Define Maximum Sentence Length

```python
sent_length = 8
```

Here, we specify that every sentence should have **8 positions**.

- If a sentence has fewer than 8 words, zeros will be added.
- If it has more than 8 words, extra words will be removed.

---

## Apply Padding

```python
embedded_docs = pad_sequences(
    one_hot_repr,
    padding='pre',
    maxlen=sent_length
)
```

### Explanation

- **one_hot_repr**
  - Contains the integer representation of each sentence obtained using `one_hot()`.

- **maxlen=8**
  - Ensures every sentence has a length of **8**.

- **padding='pre'**
  - Adds zeros at the **beginning** of shorter sentences.

Example:

Before padding

```text
[123, 456, 789]
```

After padding

```text
[0, 0, 0, 0, 0, 123, 456, 789]
```

If `padding='post'` were used, zeros would be added at the end.

---

## Display the Result

```python
print(embedded_docs)
```

Prints the padded sequences.

Example Output:

```text
[
 [0 0 0 0 123 456 789 222]
 [0 0 0 123 456 789 901 567]
 [0 0 123 852 789 145 321 654]
]
```

Now every sentence has the same length and is ready to be passed to the **Embedding Layer**.

---

## Workflow

```text
Sentence
    ↓
One-Hot Encoding
    ↓
Integer IDs
    ↓
Padding
    ↓
Equal Length Sequences
    ↓
Embedding Layer
```

---

## Key Points

- Neural networks require input sequences of **equal length**.
- `pad_sequences()` is used to make all sequences the same size.
- `maxlen` specifies the required sequence length.
- `padding='pre'` adds zeros at the beginning.
- The padded sequences become the input to the **Embedding Layer**.

# Feature Representation using Embedding Layer

## Define Embedding Dimension

```python
dim = 10
```

### Explanation

The embedding dimension defines the **size of the vector** that will represent each word.

Here,

```text
Embedding Dimension = 10
```

This means every word will be converted into a vector containing **10 numerical values**.

Example:

```text
good

↓

[0.12, -0.45, 0.87, ..., 0.23]
```

Instead of representing a word using a single number, the Embedding Layer learns a dense vector representation.

---

## Create the Model

```python
model = Sequential()
```

Creates an empty Sequential model.

Layers will be added one after another.

---

## Add the Embedding Layer

```python
model.add(
    Embedding(
        voc_size,
        dim,
        input_length=sent_length
    )
)
```

### Explanation of Parameters

### `voc_size`

Represents the vocabulary size.

Example:

```text
voc_size = 10000
```

The Embedding layer creates an **Embedding Matrix** of size:

```text
10000 × 10
```

That means every one of the 10,000 possible words gets its own 10-dimensional vector.

---

### `dim`

Specifies the embedding dimension.

```text
dim = 10
```

Each word is represented by a vector of length **10**.

---

### `input_length`

```text
input_length = sent_length
```

Specifies the length of every input sentence.

Since

```python
sent_length = 8
```

every input sentence contains **8 word positions**.

---

## Compile the Model

```python
model.compile(
    optimizer='adam',
    loss='mse'
)
```

### Explanation

Since we are only testing the Embedding Layer, compilation is required before prediction.

- **Optimizer:** Adam
- **Loss Function:** Mean Squared Error (MSE)

At this stage, these values are not important because we are not training the model.

---

## View Model Summary

```python
model.summary()
```

Displays information about the model.

Example:

```text
Embedding Layer

Input Shape : (None, 8)

Output Shape : (None, 8, 10)

Parameters : 100000
```

### Understanding the Output Shape

```text
(None, 8, 10)
```

- **None** → Batch size (can be any number of sentences)
- **8** → Number of words in each sentence
- **10** → Embedding dimension

This means each sentence is converted into an **8 × 10 matrix**.

---

## Generate Word Embeddings

```python
model.predict(embedded_docs)
```

The Embedding Layer converts every integer word ID into a dense vector.

Example

Input

```text
[0, 0, 0, 12, 54, 98, 32, 65]
```

Output

```text
[
 [0.11, 0.45, ...],
 [0.23, 0.71, ...],
 ...
]
```

Each integer becomes a vector of length **10**.

---

## View First Sentence

```python
embedded_docs[0]
```

Displays the first padded sentence.

Example

```text
[0, 0, 0, 0, 123, 456, 789, 222]
```

These are integer IDs, **not embeddings**.

---

## Check Shape of the Input

```python
print(embedded_docs.shape)
```

Example Output

```text
(7, 8)
```

Explanation:

- **7** → Total number of sentences.
- **8** → Each sentence has 8 word positions after padding.

---

## Check Shape of One Sentence

```python
print(embedded_docs[0].shape)
```

Output

```text
(8,)
```

This means one sentence contains **8 integer values**.

---

## Check Model Input Shape

```python
print(model.input_shape)
```

Output

```text
(None, 8)
```

Explanation:

- **None** → Any number of input samples.
- **8** → Every input sentence must have length 8.

---

## Predict on a Single Sentence

```python
model.predict(embedded_docs[0])
```

This tries to predict using **only one sentence**.

However, Keras expects input in the form:

```text
(Number of Samples, Sentence Length)
```

Example:

```text
(1, 8)
```

Instead of

```text
(8,)
```

Therefore, the correct way is:

```python
model.predict(np.array([embedded_docs[0]]))
```

or

```python
model.predict(embedded_docs[0].reshape(1, 8))
```

This converts one sentence into a batch containing one sample.

---

## Workflow

```text
Sentence
      ↓
One-Hot Encoding
      ↓
Integer IDs
      ↓
Padding
      ↓
Embedding Layer
      ↓
Dense Word Vectors
      ↓
RNN / LSTM / GRU
```

---

## Key Points

- The **Embedding Layer** converts integer word IDs into dense vectors.
- `voc_size` defines the number of unique words.
- `dim` defines the size of each word vector.
- `input_length` specifies the sentence length.
- Input shape = `(Number of Sentences, Sentence Length)`.
- Output shape = `(Number of Sentences, Sentence Length, Embedding Dimension)`.
- The Embedding Layer learns these vectors automatically during training.
````


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Omkar\Desktop\Python\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step


array([[[ 0.02469809, -0.01936586, -0.0059386 ,  0.01853449,
         -0.0176497 , -0.02059682,  0.03889086, -0.02449114,
          0.03774097, -0.01590803],
        [ 0.02469809, -0.01936586, -0.0059386 ,  0.01853449,
         -0.0176497 , -0.02059682,  0.03889086, -0.02449114,
          0.03774097, -0.01590803],
        [ 0.02469809, -0.01936586, -0.0059386 ,  0.01853449,
         -0.0176497 , -0.02059682,  0.03889086, -0.02449114,
          0.03774097, -0.01590803],
        [ 0.02469809, -0.01936586, -0.0059386 ,  0.01853449,
         -0.0176497 , -0.02059682,  0.03889086, -0.02449114,
          0.03774097, -0.01590803],
        [ 0.02317213,  0.0214494 ,  0.00622343, -0.04059467,
         -0.01631869, -0.03505401, -0.00430159, -0.03932978,
          0.00139972,  0.01403892],
        [-0.02156481, -0.04891067,  0.0140234 ,  0.0020705 ,
          0.03717965, -0.0399974 , -0.00108358,  0.02684237,
         -0.03518494, -0.03460181],
        [ 0.01280744, -0.03081871,  0.03495503,  0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 6957, 9577, 8957, 6915], dtype=int32)

In [16]:
print(embedded_docs.shape)
print(embedded_docs[0].shape)
print(model.input_shape)

(7, 8)
(8,)
(7, 8)


# Assignment Summary: Word Embedding Representation using Keras

In this assignment, we learned how to convert **text data into numerical vector representations** so that it can be used by Deep Learning models like **Simple RNN, LSTM, and GRU**.

---

# 1. Created a Small Text Dataset

- Defined a list of sample sentences.
- These sentences act as the input text (corpus).

### Example

```text
the glass of milk
I am a good developer
your videos are good
```

---

# 2. Applied One-Hot Encoding

Used TensorFlow's `one_hot()` function to convert each word into a unique integer ID.

### Example

Input:

```text
the glass of milk
```

Output:

```text
[234, 567, 123, 890]
```

> **Note:** TensorFlow's `one_hot()` in this context returns **integer word IDs**, not binary one-hot vectors.

---

# 3. Applied Sequence Padding

Since every sentence has a different number of words, we used `pad_sequences()`.

### Purpose

- Make every sentence the same length.
- Required because neural networks expect fixed-size input.

### Example

Before Padding:

```text
[234, 567, 123]
```

After Padding (`maxlen = 8`):

```text
[0, 0, 0, 0, 0, 234, 567, 123]
```

---

# 4. Created an Embedding Layer

Used Keras' `Embedding` layer.

```python
Embedding(voc_size, embedding_dimension, input_length)
```

### Example

```python
Embedding(10000, 10, input_length=8)
```

### Meaning

- **Vocabulary Size:** 10,000 words
- **Embedding Dimension:** Each word is represented by a **10-dimensional dense vector**
- **Input Length:** Every sentence contains **8 words**

---

# 5. Built a Simple Sequential Model

Created a Sequential model containing only the Embedding layer.

```text
Sequential
      │
      ▼
Embedding Layer
```

This was done to understand how the Embedding layer transforms input sequences before using it with RNN-based models.

---

# 6. Converted Integer IDs into Dense Vectors

Passed the padded sequences through the Embedding layer.

### Input

```text
[0, 0, 234, 567, 123]
```

### Output

```text
[
 [0.12, 0.45, ...],
 [0.31, 0.76, ...],
 [0.28, 0.19, ...],
 [0.84, 0.52, ...],
 [0.17, 0.68, ...]
]
```

Each integer ID is converted into a **10-dimensional dense vector**.

---

# 7. Understood Input and Output Shapes

### Input Shape

```text
(Number of Sentences, Sentence Length)
```

Example:

```text
(7, 8)
```

### Output Shape

```text
(Number of Sentences,
 Sentence Length,
 Embedding Dimension)
```

Example:

```text
(7, 8, 10)
```

### Meaning

- **7** sentences
- **8** words in each sentence
- **10** numerical values representing each word

---

# 8. Learned Why Embedding is Better than One-Hot Encoding

## One-Hot Encoding

- Assigns each word a unique integer ID.
- Does **not** capture semantic meaning or relationships between words.

## Embedding

- Converts words into dense numerical vectors.
- Similar words tend to have similar vector representations.
- Learns meaningful representations automatically during model training.
- Produces compact and efficient feature vectors.

---

# Complete Workflow

```text
Text Sentences
      │
      ▼
One-Hot Encoding
      │
      ▼
Integer Word IDs
      │
      ▼
Sequence Padding
      │
      ▼
Equal-Length Sequences
      │
      ▼
Embedding Layer
      │
      ▼
Dense Word Vectors
      │
      ▼
Ready for Simple RNN / LSTM / GRU
```

---

# Key Concepts Learned

- Text preprocessing for Deep Learning
- One-Hot Encoding using TensorFlow
- Vocabulary Size (`voc_size`)
- Sequence Padding (`pad_sequences`)
- Embedding Layer
- Embedding Dimension
- Input and Output Shapes of an Embedding Layer
- Converting text into dense numerical vectors before feeding it into RNN-based models

---

# Important Takeaway ⭐

This assignment **did not train a Simple RNN, LSTM, or GRU model**. Its primary objective was to understand **how raw text is transformed into dense numerical vector representations** using the **Keras Embedding Layer**.

The **Embedding Layer** serves as the first stage of most NLP deep learning models, converting words into meaningful dense vectors that can then be processed by sequence models such as **Simple RNN, LSTM, and GRU**.
````
